### ISSUE TITLE
VapourSynth R55+ fails to compile

### ISSUE THREAD

**Issue by rlaphoenix** [Irrational-Encoding-Wizardry/install-vapoursynth-action#5]
I used the 'Run tests' GitHub workflow to test R55 by manually adding support under vs_versions. It used zimg 2.9, maybe it needs 3.0?

<details>
  <summary>Error Log</summary>

  ```
  Installing Building Tool for: vs@R55
    Ensuring existence of nasm...
    /usr/bin/sudo apt-get install --yes nasm
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following NEW packages will be installed:
      nasm
    0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
    Need to get 359 kB of archives.
    After this operation, 2831 kB of additional disk space will be used.
    Get:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 nasm amd64 2.13.02-0.1 [359 kB]
    Fetched 359 kB in 0s (3441 kB/s)
    Selecting previously unselected package nasm.
    (Reading database ... 
    (Reading database ... 5%
    (Reading database ... 10%
    (Reading database ... 15%
    (Reading database ... 20%
    (Reading database ... 25%
    (Reading database ... 30%
    (Reading database ... 35%
    (Reading database ... 40%
    (Reading database ... 45%
    (Reading database ... 50%
    (Reading database ... 55%
    (Reading database ... 60%
    (Reading database ... 65%
    (Reading database ... 70%
    (Reading database ... 75%
    (Reading database ... 80%
    (Reading database ... 85%
    (Reading database ... 90%
    (Reading database ... 95%
    (Reading database ... 100%
    (Reading database ... 252008 files and directories currently installed.)
    Preparing to unpack .../nasm_2.13.02-0.1_amd64.deb ...
    Unpacking nasm (2.13.02-0.1) ...
    Setting up nasm (2.13.02-0.1) ...
    Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
    Cloning vs
    /usr/bin/git clone https://github.com/vapoursynth/vapoursynth --depth 1 --branch R55 /tmp/vs-git/
    Cloning into '/tmp/vs-git'...
    Note: switching to '16a8d6d041a746c928a4e21e079a2ffeeed54f6b'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:
    
      git switch -c <new-branch-name>
    
    Or undo this operation with:
    
      git switch -
    
    Turn off this advice by setting config variable advice.detachedHead to false
    
    Compiling vs
    /tmp/vs-git/autogen.sh
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in '.'.
    libtoolize: copying file './ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
    libtoolize: copying file 'm4/libtool.m4'
    libtoolize: copying file 'm4/ltoptions.m4'
    libtoolize: copying file 'm4/ltsugar.m4'
    libtoolize: copying file 'm4/ltversion.m4'
    libtoolize: copying file 'm4/lt~obsolete.m4'
    autoreconf: running: /usr/bin/autoconf --force
    autoreconf: configure.ac: not using Autoheader
    autoreconf: running: automake --add-missing --copy --force-missing
    configure.ac:9: installing './compile'
    configure.ac:9: installing './config.guess'
    configure.ac:9: installing './config.sub'
    configure.ac:6: installing './install-sh'
    configure.ac:6: installing './missing'
    Makefile.am: installing './depcomp'
    autoreconf: Leaving directory `.'
    /tmp/vs-git/configure --prefix=/usr --disable-vsscript --disable-python-module
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether make supports nested variables... (cached) yes
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 3145728
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) gcc3
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... gcc3
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /usr/bin/ld -m elf_x86_64
    checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
    checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking for g++ option to produce PIC... -fPIC -DPIC
    checking if g++ PIC flag -fPIC -DPIC works... yes
    checking if g++ static flag -static works... yes
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking dynamic linker characteristics... (cached) GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking whether gcc is Clang... no
    checking whether pthreads work with "-pthread" and "-lpthread"... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking whether more special flags are required for pthreads... no
    checking for PTHREAD_PRIO_INHERIT... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for ZIMG... yes
    checking for library containing dlopen... -ldl
    checking for sched_getaffinity... yes
    checking for cpuset_getaffinity... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating pc/vapoursynth.pc
    config.status: creating Makefile
    config.status: executing depfiles commands
    config.status: executing libtool commands
    /usr/bin/make
      CXX      src/core/libvapoursynth_la-audiofilters.lo
    In file included from src/core/audiofilters.cpp:31:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-averageframesfilter.lo
    In file included from src/core/averageframesfilter.cpp:31:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-boxblurfilter.lo
    In file included from src/core/boxblurfilter.cpp:27:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-cpufeatures.lo
      CXX      src/core/libvapoursynth_la-genericfilters.lo
    In file included from src/core/genericfilters.cpp:33:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/kernel/libvapoursynth_la-cpulevel.lo
      CXX      src/core/kernel/libvapoursynth_la-generic.lo
      CC       src/core/kernel/libvapoursynth_la-merge.lo
    In file included from src/core/kernel/merge.c:23:0:
    ./include/VSHelper4.h: In function ‘vsh_isSameVideoPresetFormat’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                                                                                                                                   ^~
    src/core/kernel/merge.c: In function ‘vs_mask_merge_premul_word_c’:
    src/core/kernel/merge.c:246:13: warning: unused variable ‘shift’ [-Wunused-variable]
         uint8_t shift = shift_table[depth - 9];
                 ^~~~~
    src/core/kernel/merge.c:245:14: warning: unused variable ‘div’ [-Wunused-variable]
         uint32_t div = div_table[depth - 9];
                  ^~~
      CC       src/core/kernel/libvapoursynth_la-planestats.lo
    In file included from src/core/kernel/planestats.c:23:0:
    ./include/VSHelper4.h: In function ‘vsh_isSameVideoPresetFormat’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                                                                                                                                   ^~
      CC       src/core/kernel/libvapoursynth_la-transpose.lo
    In file included from src/core/kernel/transpose.h:26:0,
                     from src/core/kernel/transpose.c:28:
    ./include/VSHelper4.h: In function ‘vsh_isSameVideoPresetFormat’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                                                                                                                                   ^~
      CXX      src/core/libvapoursynth_la-lutfilters.lo
    In file included from src/core/lutfilters.cpp:29:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-mergefilters.lo
    In file included from src/core/mergefilters.cpp:30:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-reorderfilters.lo
    In file included from src/core/reorderfilters.cpp:25:0:
    ./include/VSHelper4.h: In function ‘bool vsh::isSameVideoPresetFormat(int, const VSVideoFormat*, VSCore*, const VSAPI*)’:
    ./include/VSHelper4.h:99:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return vsapi->queryVideoFormatID(v->colorFamily, v->sampleType, v->bitsPerSample, v->subSamplingW, v->subSamplingH, core) == presetFormat;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      CXX      src/core/libvapoursynth_la-settings.lo
      CXX      src/core/libvapoursynth_la-simplefilters.lo
    /usr/include/c++/7/bits/unordered_map.h:183:7: note: candidate: std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>&&) [with _Key = std::__cxx11::basic_string<char>; _Tp = zimg_cpu_type_e; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, zimg_cpu_type_e> >]
           unordered_map(unordered_map&&) = default;
           ^~~~~~~~~~~~~
    /usr/include/c++/7/bits/unordered_map.h:183:7: note:   candidate expects 1 argument, 17 provided
    /usr/include/c++/7/bits/unordered_map.h:180:7: note: candidate: std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(const std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>&) [with _Key = std::__cxx11::basic_string<char>; _Tp = zimg_cpu_type_e; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, zimg_cpu_type_e> >]
           unordered_map(const unordered_map&) = default;
           ^~~~~~~~~~~~~
    /usr/include/c++/7/bits/unordered_map.h:180:7: note:   candidate expects 1 argument, 17 provided
    /usr/include/c++/7/bits/unordered_map.h:171:2: note: candidate: template<class _InputIterator> std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(_InputIterator, _InputIterator, std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&)
      unordered_map(_InputIterator __first, _InputIterator __last,
      ^~~~~~~~~~~~~
    /usr/include/c++/7/bits/unordered_map.h:171:2: note:   template argument deduction/substitution failed:
    src/core/vsresize.cpp:65:1: note:   candidate expects 6 arguments, 17 provided
     };
     ^
    In file included from /usr/include/c++/7/unordered_map:48:0,
                     from src/core/vsresize.cpp:28:
    /usr/include/c++/7/bits/unordered_map.h:150:7: note: candidate: std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::__cxx11::basic_string<char>; _Tp = zimg_cpu_type_e; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, zimg_cpu_type_e> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::__cxx11::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::__cxx11::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::__cxx11::basic_string<char>, zimg_cpu_type_e> >]
           unordered_map(size_type __n,
           ^~~~~~~~~~~~~
    /usr/include/c++/7/bits/unordered_map.h:150:7: note:   candidate expects 4 arguments, 17 provided
    /usr/include/c++/7/bits/unordered_map.h:140:7: note: candidate: std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map() [with _Key = std::__cxx11::basic_string<char>; _Tp = zimg_cpu_type_e; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, zimg_cpu_type_e> >]
           unordered_map() = default;
           ^~~~~~~~~~~~~
    /usr/include/c++/7/bits/unordered_map.h:140:7: note:   candidate expects 0 arguments, 17 provided
    Makefile:1273: recipe for target 'src/core/libvapoursynth_la-vsresize.lo' failed
    make: *** [src/core/libvapoursynth_la-vsresize.lo] Error 1
  Error: The process '/usr/bin/make' failed with exit code 2
      at ExecState._setResult (/home/runner/work/install-vapoursynth-action/install-vapoursynth-action/dist/build.js:6084:25)
      at ExecState.CheckComplete (/home/runner/work/install-vapoursynth-action/install-vapoursynth-action/dist/build.js:6067:18)
      at ChildProcess.<anonymous> (/home/runner/work/install-vapoursynth-action/install-vapoursynth-action/dist/build.js:5961:27)
      at ChildProcess.emit (node:events:513:28)
      at maybeClose (node:internal/child_process:1100:16)
      at Socket.<anonymous> (node:internal/child_process:458:11)
      at Socket.emit (node:events:513:28)
      at Pipe.<anonymous> (node:net:301:12)
  Error: installation failed unexpectedly.
  Error: Process completed with exit code 1.
  ```
</details>

**Comment by rlaphoenix** [comment]
I was right, it needs to use zimg 3.0.
